[package]
name = "userinit"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "userinit"
path = "src/main.rs"
test = false
doctest = false

[dependencies]
userlib.workspace = true

[lints]
workspace = true
