site_name: COCONUT-SVSM
theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist

nav:
  - Documentation Home: 'index.md'
  - Building and launching:
    - 'installation/INSTALL.md'
  - Build Recipe Documentation:
    - 'installation/BUILD_RECIPES.md'

  - Developer Information:
    - 'developer/DOC-GUIDELINES.md'
    - Development Plan Overview: 'developer/DEVELOPMENT-PLAN.md'
    - Rustdoc Guidelines: 'developer/RUSTDOC-GUIDELINES.md'
    - Fuzzing: 'developer/FUZZING.md'
    - Contributing to COCONUT-SVSM: 'developer/CONTRIBUTING.md'
    - Formal Verification: 'developer/VERIFICATION.md'
    - Attestation: 'developer/ATTESTATION.md'
    - Persistence: 'developer/PERSISTENCE.md'
  - 'COCONUT-SVSM Rustdoc': 'rustdoc/svsm'
