name: Verification

# Only run this workflow when manually triggered
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Verification Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install verus toolchains
        run: ./scripts/vinstall.sh --prebuilt-verusfmt

      - name: Format spec/proof code
        run: |
          verusfmt --check `find ./ -name *.verus.rs` --verus-only

      # cargo-v doesn't propagate the `cargo build` exit code, so we need
      # to check stderr for errors.
      # When https://github.com/microsoft/verismo/issues/23 will be fixed
      # we can remove it.
      - name: Verify svsm with verus
        run: |
          cargo verify 2>&1 | tee verify.log
          ! grep -q 'cargo build failed' verify.log
        working-directory: kernel

      - name: Verify extra proof libs with verus
        run: |
          cargo verify 2>&1 | tee verify.log
          ! grep -q 'cargo build failed' verify.log
        working-directory: verification/verify_proof
