name: SignedOff

on: [pull_request]

jobs:
  check:
    name: Check commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check commits
        run: |
          git fetch
          git fetch origin ${{ github.event.pull_request.base.ref }}
          ${GITHUB_WORKSPACE}/scripts/check-signed-off.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
