name: SPDX

on: [pull_request]

jobs:
  check:
    name: Check SPDX headers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check new files for SPDX headers
        run: |
          git fetch
          git fetch origin ${{ github.event.pull_request.base.ref }}
          ${GITHUB_WORKSPACE}/scripts/check-spdx.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
