name: Verification	

on:	
  pull_request:	
    branches: [ "main-verify" ]

env:	
  CARGO_TERM_COLOR: always	

jobs:	
  check:	
    name: Verification Check	
    runs-on: ubuntu-latest	
    steps:	
      - name: Checkout	
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install specified rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: '1.91.0'
            target: x86_64-unknown-none
            profile: minimal
            override: true
            components: rustfmt, rust-src, clippy

      - name: Install verus toolchains	
        run: ./scripts/vinstall.sh	

      - name: Format rust code
        run: verusfmt --check `find ./ -name *.verus.rs`

      - name: Verify svsm with verus	
        run: cargo verify	
        working-directory: kernel	

      - name: Verify extra proof libs with verus	
        run: cargo verify	
        working-directory: verify_proof	
